# Generated by Django 5.1.1 on 2024-09-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="send_indicator",
            field=models.PositiveSmallIntegerField(
                blank=True, editable=False, null=True, verbose_name="Индикатор отправки"
            ),
        ),
    ]
